# Generated by Django 5.1.3 on 2025-04-23 05:31

import django.db.models.deletion
import waterrejuvenation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_restore_user_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterbodiesFileUploadLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=waterrejuvenation.models.excel_file_path)),
                ('excel_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(limit_choices_to={'app_type': 'waterbody', 'enabled': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wate_rej_excel_files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excel File',
                'verbose_name_plural': 'Excel Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
