# Generated by Django 5.1.3 on 2025-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterrejuvenation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodiesfileuploadlog',
            name='process',
            field=models.BooleanField(default=False),
        ),
    ]
