# Generated by Django 5.1.3 on 2025-04-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0001_initial'),
        ('projects', '0002_restore_user_relations'),
        ('waterrejuvenation', '0002_waterbodiesfileuploadlog_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterbodiesDesiltingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_ngo', models.CharField(max_length=255)),
                ('Taluka', models.CharField(max_length=255, null=True)),
                ('Village', models.CharField(max_length=255, null=True)),
                ('waterbody_name', models.CharField(max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('slit_excavated', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.BooleanField(default=False)),
                ('waterbody_id', models.CharField(max_length=255, null=True)),
                ('closest_wb_lat', models.FloatField()),
                ('closest_wb_long', models.FloatField()),
                ('intersecting_mws', models.CharField(max_length=255, null=True)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoadmin.district')),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoadmin.state')),
                ('project', models.ForeignKey(limit_choices_to={'app_type': 'waterbody', 'enabled': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wate_dslit', to='projects.project')),
            ],
        ),
    ]
