# Generated by Django 5.1.3 on 2025-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterrejuvenation', '0003_waterbodiesdesiltinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbodiesdesiltinglog',
            name='closest_wb_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='waterbodiesdesiltinglog',
            name='closest_wb_long',
            field=models.FloatField(null=True),
        ),
    ]
