# Generated by Django 5.1.3 on 2025-04-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterrejuvenation', '0004_alter_waterbodiesdesiltinglog_closest_wb_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbodiesdesiltinglog',
            name='District',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='waterbodiesdesiltinglog',
            name='State',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
