# Generated by Django 5.1.3 on 2025-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterrejuvenation', '0005_alter_waterbodiesdesiltinglog_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodiesdesiltinglog',
            name='distance_closest_wb_pixel',
            field=models.IntegerField(null=True),
        ),
    ]
