# Generated by Django 5.1.3 on 2025-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterrejuvenation', '0006_waterbodiesdesiltinglog_distance_closest_wb_pixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodiesdesiltinglog',
            name='excel_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
