# Generated by Django 5.1.3 on 2025-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterrejuvenation', '0007_waterbodiesdesiltinglog_excel_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodiesfileuploadlog',
            name='is_closest_wp',
            field=models.BooleanField(default=True),
        ),
    ]
