# Generated by Django 5.2 on 2025-04-17 09:53

import django.db.models.deletion
from django.db import migrations, models


def copy_project_ids(apps, schema_editor):
    """Copy project_id values to the new project ForeignKey."""
    UserProjectGroup = apps.get_model('users', 'UserProjectGroup')
    Project = apps.get_model('projects', 'Project')
    
    for upg in UserProjectGroup.objects.all():
        try:
            # Try to find the project with this ID
            project = Project.objects.get(id=upg.project_id_old)
            upg.project = project
            upg.save()
        except Project.DoesNotExist:
            # If project doesn't exist, use a default or handle as needed
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_restore_user_relations'),
        ('users', '0001_initial'),
    ]

    operations = [
        # First rename the existing column to avoid conflicts
        migrations.RenameField(
            model_name='userprojectgroup',
            old_name='project_id',
            new_name='project_id_old',
        ),
        
        # Add the new ForeignKey field
        migrations.AddField(
            model_name='userprojectgroup',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        
        # Run the data migration to copy values
        migrations.RunPython(copy_project_ids),
        
        # Make the field non-nullable now that data is copied
        migrations.AlterField(
            model_name='userprojectgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        
        # Update the unique constraint
        migrations.AlterUniqueTogether(
            name='userprojectgroup',
            unique_together={('user', 'project')},
        ),
        
        # Remove the old field
        migrations.RemoveField(
            model_name='userprojectgroup',
            name='project_id_old',
        ),
    ]