# Generated by Django 5.1.5 on 2025-03-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='odk_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
