# Generated by Django 5.1.5 on 2025-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geojson_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_type', models.CharField(choices=[('plantation', 'Plantations'), ('watershed', 'Watershed Planning')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
