# Generated by Django 5.2 on 2025-04-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoadmin', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geojson_path', models.CharField(blank=True, max_length=512, null=True)),
                ('app_type', models.CharField(choices=[('plantation', 'Plantations'), ('watershed', 'Watershed Planning'), ('waterbody', 'Waterbody Rejuvenation')], max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_id', models.IntegerField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organization.organization')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
