# Generated by Django 5.2 on 2025-08-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0004_userapikey_api_key'),
        ('projects', '0002_restore_user_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block'),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district'),
        ),
        migrations.AddField(
            model_name='project',
            name='district_soi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.districtsoi'),
        ),
        migrations.AddField(
            model_name='project',
            name='state_soi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.statesoi'),
        ),
        migrations.AddField(
            model_name='project',
            name='tehsil_soi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.tehsilsoi'),
        ),
    ]
