# Generated by Django 5.2 on 2025-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_restore_user_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_type',
            field=models.CharField(choices=[('plantation', 'Plantations'), ('watershed', 'Watershed Planning'), ('waterbody', 'Waterbody Rejuvenation'), ('community_engagement', 'Community Engagement')], max_length=255),
        ),
    ]
