# Generated by Django 5.1.5 on 2025-03-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project_app', models.ForeignKey(limit_choices_to={'app_type': 'plantation'}, on_delete=django.db.models.deletion.CASCADE, related_name='plantation_profiles', to='projects.projectapp')),
            ],
        ),
    ]
