# Generated by Django 5.1.5 on 2025-03-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoadmin", "0001_initial"),
        ("plans", "0002_remove_planapp_project_app_planapp_enabled_and_more"),
        ("plantations", "0004_remove_kmlfile_project_app_kmlfile_project"),
        ("projects", "0003_plantationprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantationprofile",
            name="project_app",
        ),
        migrations.RemoveField(
            model_name="plantationprofile",
            name="config",
        ),
        migrations.AddField(
            model_name="plantationprofile",
            name="config_user_input",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="plantationprofile",
            name="config_variables",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="plantationprofile",
            name="config_weight",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="plantationprofile",
            name="project",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"app_type": "plantation"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantation_profiles",
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("plantation", "Plantations"),
                    ("watershed", "Watershed Planning"),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geoadmin.state",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProjectApp",
        ),
    ]
