# Generated by Django 5.2 on 2025-06-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0001_initial'),
        ('projects', '0003_alter_project_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block'),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district'),
        ),
    ]
