# Generated by Django 5.1.5 on 2025-03-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geoadmin", "0001_initial"),
        ("projects", "0004_remove_plantationprofile_project_app_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geoadmin.state",
            ),
        ),
    ]
