# Generated by Django 5.0 on 2025-03-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_plantationprofile_project_app_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlantationProfile",
        ),
    ]
