# Generated by Django 5.2 on 2025-06-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0001_initial'),
        ('projects', '0004_project_block_project_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block'),
        ),
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district'),
        ),
    ]
