# Generated by Django 5.2 on 2025-08-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_block_project_district_project_district_soi_and_more'),
        ('projects', '0005_alter_project_block_alter_project_district'),
    ]

    operations = [
    ]
