name: black
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - affine=2.4.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alsa-lib=1.2.8
  - amqp=2.6.1
  - anyascii=0.3.2
  - asgiref=3.8.1
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=24.3.0
  - billiard=3.6.4.0
  - blas=1.0
  - blosc=1.21.3
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - boto3=1.37.10
  - botocore=1.37.10
  - bottleneck=1.4.2
  - branca=0.6.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cachetools=5.5.1
  - cairo=1.16.0
  - celery=4.4.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - cfitsio=4.2.0
  - charset-normalizer=3.3.2
  - click=8.1.8
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1
  - click-repl=0.2.0
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - contourpy=1.3.1
  - curl=8.12.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - cytoolz=1.0.1
  - dask=2023.3.0
  - dask-core=2023.3.0
  - dbus=1.13.18
  - deprecated=1.2.18
  - distributed=2023.3.0
  - django=5.2
  - django-cors-headers=4.7.0
  - djangorestframework=3.15.2
  - double-conversion=3.3.1
  - drf-yasg=1.21.7
  - earthengine-api=1.5.9
  - expat=2.7.0
  - fftw=3.3.10
  - fiona=1.10.1
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.5.0
  - fsspec=2025.3.2
  - gdal=3.6.2
  - geetools=1.15.0
  - geojson=3.2.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - google-api-core=2.24.2
  - google-api-python-client=2.165.0
  - google-auth=2.38.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.1.0
  - google-crc32c=1.6.0
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.69.2
  - graphite2=1.3.14
  - greenlet=3.1.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - httplib2=0.22.0
  - icu=70.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - inflection=0.5.1
  - jack=1.9.22
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - json-c=0.16
  - kealib=1.5.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - kombu=4.6.3
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libaec=1.1.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libcap=2.67
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.7.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgdal=3.6.2
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran-ng=8.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.1
  - libglu=9.0.0
  - libglvnd=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.53
  - libiconv=1.18
  - libjpeg-turbo=2.1.4
  - libkml=1.3.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - liblzma=5.8.1
  - libnetcdf=4.9.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libntlm=1.6
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=15.2
  - libprotobuf=3.20.3
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libspatialite=5.0.1
  - libsqlite=3.45.3
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libtool=2.5.4
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.10.1
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - minizip=4.0.3
  - mpg123=1.32.9
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - ncurses=6.5
  - networkx=3.4.2
  - nspr=4.36
  - nss=3.100
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.0
  - openldap=2.6.5
  - openssl=3.1.8
  - packaging=24.2
  - pandas=2.2.3
  - partd=1.4.2
  - patsy=1.0.1
  - pcraster=4.4.0
  - pcre2=10.40
  - pillow=9.4.0
  - pip=25.0
  - pixman=0.44.2
  - ply=3.11
  - poppler=23.03.0
  - poppler-data=0.4.11
  - postgresql=15.2
  - proj=9.1.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=3.20.3
  - psutil=7.0.0
  - pthread-stubs=0.3
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyogrio=0.10.0
  - pyopenssl=25.0.0
  - pyparsing=3.2.0
  - pyproj=3.5.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqt6-sip=13.9.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.8
  - rasterio=1.4.3
  - readline=8.2
  - requests=2.32.3
  - rsa=4.7.2
  - s3transfer=0.11.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - shapely=2.0.1
  - simplejson=3.19.2
  - sip=6.7.12
  - six=1.17.0
  - sortedcontainers=2.4.0
  - sqlalchemy=2.0.37
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - statsmodels=0.14.4
  - tblib=3.1.0
  - threadpoolctl=3.5.0
  - tiledb=2.13.2
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=1.0.0
  - tornado=6.4.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2025b
  - tzdata=2025a
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - uriparser=0.9.7
  - uritemplate=4.1.1
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.5
  - wheel=0.45.1
  - wrapt=1.17.2
  - xarray=2024.3.0
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xee=0.0.20
  - xerces-c=3.2.4
  - xkeyboard-config=2.38
  - xmltodict=0.14.2
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.0
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-libxxf86vm=1.1.5
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.20.2
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - yaml=0.2.5
  - yamlable=1.1.1
  - yarl=1.18.0
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - cryptography==44.0.1
      - django-environ==0.12.0
      - djangorestframework-simplejwt==5.5.0
      - drf-nested-routers==0.94.1
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - h11==0.16.0
      - lxml==5.3.2
      - outcome==1.3.0.post0
      - psycopg==3.2.6
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyjwt==2.9.0
      - pymannkendall==1.4.3
      - python-docx==1.1.2
      - selenium==4.32.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typing-inspection==0.4.0
      - vine==1.3.0
      - websocket-client==1.8.0
      - wsproto==1.2.0
