parts = ['eyJ0eXAiOiJKV1QiLCJh', 'bGciOiJSUzI1NiIsIng1', 'dCI6IkpZaEFjVFBNWl9M', 'WDZEQmxPV1E3SG4wTmVY',
         'RSIsImtpZCI6IkpZaEFj', 'VFBNWl9MWDZEQmxPV1E3', 'SG4wTmVYRSJ9.eyJhdWQ', 'iOiJodHRwczovL2FuYWx',
         '5c2lzLndpbmRvd3MubmV', '0L3Bvd2VyYmkvYXBpIiw', 'iaXNzIjoiaHR0cHM6Ly9', 'zdHMud2luZG93cy5uZXQ',
         'vZWIxMTkwYWQtN2RlZi0', '0MTA4LTlmYTQtM2JkYzI', '3ZDFmN2FjLyIsImlhdCI', '6MTc1NjMyMzgzOCwibmJ',
         'mIjoxNzU2MzIzODM4LCJ', 'leHAiOjE3NTYzMjg1MDU', 'sImFjY3QiOjAsImFjciI', '6IjEiLCJhaW8iOiJBY1F',
         'BTy84WkFBQUFpYTYva0h', 'YZ3ZJa2gvTG1jYzJkQ1R', 'kTmtNaE9kWmQ1ejRtbEh', 'DS0pKcDFNbThueU9XS2N',
         'SWU5mc3E4eUFINmdWSFZ', 'na3N1Z092aEg4alhNczR', 'yQWg2amtxaWRYRmJEd1N', 'vU2tTcVU1cXJyRThVYXp',
         'BdzE5SWNWY3NpUmFjVnJ', '3MllXYTlBWFkwODd4ajB', 'MTUEzdkRoUjBMTGdEZ2h', 'rei91c3paZUxSbnhuNWx',
         'mTitMYjFhOUtXdTBZeDl', 'VbTl0RnQzTW0xS1E5TXp', '3K2sxN2JDeS80VHd5dUF', 'uTEhlM1ZyTnRVRkVJamp',
         'oRlJSOTZBWmRMRkp6ZmN', 'HemRFa1d0S2lrIiwiYW1', 'yIjpbInB3ZCJdLCJhcHB', 'pZCI6Ijk0M2RhOTcxLTM',
         '3ODYtNDEyZS1hMTg0LWV', 'jM2RlZGE3OWE2ZiIsImF', 'wcGlkYWNyIjoiMiIsImZ', 'hbWlseV9uYW1lIjoiRGF',
         'kaGVlY2giLCJnaXZlbl9', 'uYW1lIjoiS2FwaWwiLCJ', 'pZHR5cCI6InVzZXIiLCJ', 'pcGFkZHIiOiIyNDA1OjI',
         'wMTo0MDE0OjQzMDk6NDA', 'yYzpiYzJjOjcwMmM6Yjg', 'wZSIsIm5hbWUiOiJLYXB', 'pbCBEYWRoZWVjaCIsIm9',
         'pZCI6IjNkYzdhOWY2LTN', 'lNGQtNDMxMS04NmU4LTN', 'hYjI5N2NjMzNkMyIsIm9', 'ucHJlbV9zaWQiOiJTLTE',
         'tNS0yMS0yODU3MDU5NTM', 'wLTEwNTg2NDkyMTEtMzY', 'wNjkwNjg3OC0xODU1ODM', 'iLCJwdWlkIjoiMTAwMzI',
         'wMDM3Mzg2MkQyMCIsInJ', 'oIjoiMS5BVm9BclpBUjY', 'tOTlDRUdmcER2Y0o5SDN', 'yQWtBQUFBQUFBQUF3QUF',
         'BQUFBQUFBQmFBUDFhQUE', 'uIiwic2NwIjoidXNlcl9', 'pbXBlcnNvbmF0aW9uIiw', 'ic2lkIjoiMDA2ZjZiODk',
         'tYzVmMS1mZDZjLWE3ODc', 'tNDQ3MjVhNzhmZDkzIiw', 'ic3ViIjoiZ21lMGFodmF', 'PUkpiRzBFSV8ycFNUdlM',
         'teWEtcG1IQjBYNkhxTzd', 'tSGZydyIsInRpZCI6ImV', 'iMTE5MGFkLTdkZWYtNDE', 'wOC05ZmE0LTNiZGMyN2Q',
         'xZjdhYyIsInVuaXF1ZV9', 'uYW1lIjoiS2FwaWwuRGF', 'kaGVlY2hAc3RhcnJjb21', 'wYW5pZXMuY29tIiwidXB',
         'uIjoiS2FwaWwuRGFkaGV', 'lY2hAc3RhcnJjb21wYW5', 'pZXMuY29tIiwidXRpIjo', 'iZllSNkowUWN6a203U0p',
         'ObGZTaU9BQSIsInZlciI', '6IjEuMCIsIndpZHMiOls', 'iYjc5ZmJmNGQtM2VmOS0', '0Njg5LTgxNDMtNzZiMTk',
         '0ZTg1NTA5Il0sInhtc19', 'mdGQiOiJDYU1Ca0gzQ05', 'mMXUweHR5Rl9fRUJENmN', 'YX21lY3I1Z0J2OGhNazN',
         'nbVV3QmRYTnpiM1YwYUM', 'xa2MyMXoiLCJ4bXNfaWR', 'yZWwiOiIyOCAxIn0.D4p', '2rdZVa0Z9G3MOnYM_Xqy',
         '6FQwqJcz8TrSYvzlBVsO', 'LxPdAB5132O4IhfVAWwx', 'rsdH-YSqDYFsKHqpCb3o', 'vnKEJfuAKc0s-sCB15Wq',
         'anCzSToVNR983CVKxu59', 'ZBfbIOCjwdj9_FssRMqM', 'Sm0Gvsv_qZGjme8E7rQ0', 'q_YGm9QjGFEhuktWlpWa',
         'mRNb6byHHD2FQJy2PeK3', 'OAehZKYqNk3FAgEwVQiT', 'GNfHTPqF0ACaSW80nE2o', '1D2Nvi3k2Jb8RiOQ0fF7',
         'VDtT7XdVveUbmltgn8YZ', '02Yo6EuG8eVG-eHHPH0s', 'Ou41KVn6d31XdfKSlKpK', 'D-B4eyGxB-dY0CeqsDQ']
token = "".join(parts)  # join without spaces
print(token)
