# Generated by Django 5.1.5 on 2025-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='odk_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
