# Generated by Django 5.2 on 2025-05-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_SOI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State_SOI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block_SOI',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=255, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district_soi')),
            ],
        ),
        migrations.AddField(
            model_name='district_soi',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state_soi'),
        ),
    ]
