# Generated by Django 5.2 on 2025-07-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateSOI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('active_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictSOI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=255)),
                ('active_status', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.statesoi')),
            ],
        ),
        migrations.CreateModel(
            name='TehsilSOI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tehsil_name', models.CharField(max_length=255)),
                ('active_status', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.districtsoi')),
            ],
        ),
    ]
