# Generated by Django 5.2 on 2025-05-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0002_district_soi_state_soi_block_soi_district_soi_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block_soi',
            options={'verbose_name_plural': 'Block_SOI'},
        ),
        migrations.AlterModelOptions(
            name='district_soi',
            options={'verbose_name_plural': 'District_SOI'},
        ),
        migrations.AlterModelOptions(
            name='state_soi',
            options={'verbose_name_plural': 'State_SOI'},
        ),
    ]
