# Generated by Django 5.2 on 2025-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0003_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
