# Generated by Django 5.2 on 2025-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0003_alter_block_soi_options_alter_district_soi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_soi',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='district_soi',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state_soi',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
