# Generated by Django 5.2 on 2025-05-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0004_block_soi_active_status_district_soi_active_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block_soi',
            name='active_status',
        ),
    ]
