# Generated by Django 5.2 on 2025-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0005_remove_block_soi_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_soi',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
