# Generated by Django 5.2 on 2025-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0006_block_soi_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_soi',
            name='block_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='district_soi',
            name='district_name',
            field=models.CharField(max_length=255),
        ),
    ]
