# Generated by Django 5.1.5 on 2025-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agri_maintenance',
            fields=[
                ('agri_maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255)),
                ('plan_id', models.TextField()),
                ('plan_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status_re', models.TextField()),
                ('work_id', models.CharField(max_length=255)),
                ('corresponding_work_id', models.CharField(max_length=255)),
                ('data_agri_maintenance', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GW_maintenance',
            fields=[
                ('gw_maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255)),
                ('plan_id', models.TextField()),
                ('plan_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status_re', models.TextField()),
                ('work_id', models.CharField(max_length=255)),
                ('corresponding_work_id', models.CharField(max_length=255)),
                ('data_gw_maintenance', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SWB_maintenance',
            fields=[
                ('swb_maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255)),
                ('plan_id', models.TextField()),
                ('plan_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status_re', models.TextField()),
                ('work_id', models.CharField(max_length=255)),
                ('corresponding_work_id', models.CharField(max_length=255)),
                ('data_swb_maintenance', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SWB_RS_maintenance',
            fields=[
                ('swb_rs_maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255)),
                ('plan_id', models.TextField()),
                ('plan_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status_re', models.TextField()),
                ('work_id', models.CharField(max_length=255)),
                ('corresponding_work_id', models.CharField(max_length=255)),
                ('data_swb_rs_maintenance', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
