# Generated by Django 5.2 on 2025-04-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('facilitator_name', models.CharField(max_length=300)),
                ('plan', models.TextField(default='Default Plan')),
                ('village_name', models.CharField(max_length=300)),
                ('gram_panchayat', models.CharField(max_length=300)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
            ],
        ),
    ]
