# Generated by Django 5.1.5 on 2025-02-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoadmin', '__first__'),
        ('organization', '0001_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('facilitator_name', models.CharField(max_length=300)),
                ('plan', models.TextField(default='Default Plan')),
                ('village_name', models.CharField(max_length=300)),
                ('gram_panchayat', models.CharField(max_length=300)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
            ],
        ),
        migrations.CreateModel(
            name='PlanApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=255)),
                ('village_name', models.CharField(max_length=255)),
                ('gram_panchayat', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('project_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.projectapp')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watershed Plan',
                'verbose_name_plural': 'Watershed Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
