# Generated by Django 5.1.5 on 2025-03-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
        ("projects", "0003_plantationprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planapp",
            name="project_app",
        ),
        migrations.AddField(
            model_name="planapp",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="planapp",
            name="facilitator_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="planapp",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planapp",
            name="is_dpr_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planapp",
            name="is_dpr_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planapp",
            name="is_dpr_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planapp",
            name="project",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"enabled": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
