# Generated by Django 5.2 on 2025-04-17 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0001_initial'),
        ('organization', '0001_initial'),
        ('plans', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=255)),
                ('facilitator_name', models.CharField(blank=True, max_length=512, null=True)),
                ('village_name', models.CharField(max_length=255)),
                ('gram_panchayat', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_dpr_generated', models.BooleanField(default=False)),
                ('is_dpr_reviewed', models.BooleanField(default=False)),
                ('is_dpr_approved', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('project', models.ForeignKey(limit_choices_to={'enabled': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watershed Plan',
                'verbose_name_plural': 'Watershed Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
