# Generated by Django 5.2 on 2025-08-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoadmin', '0004_userapikey_api_key'),
        ('plans', '0002_planapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='planapp',
            name='district_soi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.districtsoi'),
        ),
        migrations.AddField(
            model_name='planapp',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='planapp',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='planapp',
            name='state_soi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.statesoi'),
        ),
        migrations.AddField(
            model_name='planapp',
            name='tehsil_soi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.tehsilsoi'),
        ),
    ]
