# Generated by Django 5.1.5 on 2025-03-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_planapp_project_app_planapp_enabled_and_more'),
        ('projects', '0004_remove_plantationprofile_project_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planapp',
            name='project',
            field=models.ForeignKey(limit_choices_to={'enabled': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project'),
        ),
    ]
