# Generated by Django 5.2 on 2025-04-17 09:42

import django.db.models.deletion
import plantations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KMLFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=plantations.models.kml_file_path)),
                ('kml_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(limit_choices_to={'app_type': 'plantation', 'enabled': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kml_files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KML File',
                'verbose_name_plural': 'KML Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantationProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('config_variables', models.JSONField(default=None, null=True)),
                ('config_weight', models.JSONField(default=None, null=True)),
                ('config_user_input', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(limit_choices_to={'app_type': 'plantation'}, on_delete=django.db.models.deletion.CASCADE, related_name='plantation_profiles', to='projects.project')),
            ],
        ),
    ]
