# Generated by Django 5.1.5 on 2025-02-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmlfile',
            name='project_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kml_files', to='projects.projectapp'),
        ),
    ]
