# Generated by Django 5.1.5 on 2025-03-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0003_initial'),
        ('projects', '0003_plantationprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmlfile',
            name='project_app',
        ),
        migrations.AddField(
            model_name='kmlfile',
            name='project',
            field=models.ForeignKey(default=1, limit_choices_to={'app_type': 'plantation', 'enabled': True}, on_delete=django.db.models.deletion.CASCADE, related_name='kml_files', to='projects.project'),
            preserve_default=False,
        ),
    ]
