# Generated by Django 5.1.5 on 2025-03-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0004_remove_kmlfile_project_app_kmlfile_project'),
        ('projects', '0004_remove_plantationprofile_project_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmlfile',
            name='project',
            field=models.ForeignKey(limit_choices_to={'app_type': 'plantation', 'enabled': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kml_files', to='projects.project'),
        ),
    ]
