# Generated by Django 5.0 on 2025-03-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantations", "0005_alter_kmlfile_project"),
        ("projects", "0005_delete_plantationprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantationProfile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("config_variables", models.JSONField(default=None, null=True)),
                ("config_weight", models.JSONField(default=None, null=True)),
                ("config_user_input", models.JSONField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        limit_choices_to={"app_type": "plantation"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantation_profiles",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
