# Generated by Django 5.2 on 2025-07-30 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_interface', '0002_alter_userlogs_app_type'),
        ('geoadmin', '0001_initial'),
        ('projects', '0005_alter_project_block_alter_project_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_interface.bot')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Community_user_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_last_accessed_community', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_engagement.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('state', 'State'), ('district', 'District'), ('block', 'Block')], max_length=10)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
            ],
            options={
                'unique_together': {('level', 'state', 'district', 'block')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='locations',
            field=models.ManyToManyField(related_name='communities', to='community_engagement.location'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('DOC', 'DOC')], max_length=255)),
                ('media_path', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('BOT', 'BOT'), ('IVR', 'IVR')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_interface.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('STORY', 'STORY'), ('GRIEVANCE', 'GRIEVANCE'), ('WORK_DEMAND', 'WORK_DEMAND'), ('CONTENT', 'CONTENT')], max_length=255)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('UNMODERATED', 'UNMODERATED'), ('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED'), ('ASSIGNED', 'ASSIGNED'), ('INPROGRESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('ACCEPTED_STAGE_1', 'ACCEPTED_STAGE_1'), ('ACCEPTED_STAGE_2', 'ACCEPTED_STAGE_2'), ('REJECTED_STAGE_1', 'REJECTED_STAGE_1'), ('REJECTED_STAGE_2', 'REJECTED_STAGE_2')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_engagement.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_engagement.item_category')),
                ('media', models.ManyToManyField(blank=True, to='community_engagement.media')),
            ],
        ),
    ]
