# Generated by Django 5.2 on 2025-08-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='misc',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
