# Generated by Django 5.2 on 2025-08-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='misc',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('UNMODERATED', 'UNMODERATED'), ('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED'), ('INPROGRESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('ACCEPTED_STAGE_1', 'ACCEPTED_STAGE_1'), ('REJECTED_STAGE_1', 'REJECTED_STAGE_1')], max_length=255),
        ),
    ]
