# Generated by Django 5.2 on 2025-06-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='location',
        ),
        migrations.RenameField(
            model_name='community_user_mapping',
            old_name='is_primary_community',
            new_name='is_last_accessed_community',
        ),
        migrations.AddField(
            model_name='media',
            name='source',
            field=models.CharField(choices=[('BOT', 'BOT'), ('IVR', 'IVR')], default='bot', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
