# Generated by Django 5.2 on 2025-06-26 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_interface', '0001_initial'),
        ('community_engagement', '0002_remove_community_location_and_more'),
        ('projects', '0005_alter_project_block_alter_project_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_interface.bot'),
        ),
        migrations.AddField(
            model_name='media',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_interface.bot'),
        ),
        migrations.AlterField(
            model_name='community',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
