# Generated by Django 5.2 on 2025-08-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0002_item_misc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('UNMODERATED', 'UNMODERATED'), ('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED'), ('INPROGRESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('ACCEPTED_STAGE_1', 'ACCEPTED_STAGE_1'), ('REJECTED_STAGE_1', 'REJECTED_STAGE_1')], max_length=255),
        ),
    ]
