# Generated by Django 5.2 on 2025-07-12 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0003_community_bot_media_bot_alter_community_project'),
        ('geoadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('UNM', 'UNM'), ('PUB', 'PUB'), ('ARC', 'ARC'), ('REJ', 'REJ')], max_length=255),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('state', 'State'), ('district', 'District'), ('block', 'Block')], max_length=10)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
            ],
            options={
                'unique_together': {('level', 'state', 'district', 'block')},
            },
        ),
        migrations.AddField(
            model_name='community',
            name='locations',
            field=models.ManyToManyField(related_name='communities', to='community_engagement.location'),
        ),
    ]
