# Generated by Django 5.2 on 2025-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0003_alter_item_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('STORY', 'STORY'), ('GRIEVANCE', 'GRIEVANCE'), ('ASSET_DEMAND', 'ASSET_DEMAND'), ('CONTENT', 'CONTENT')], max_length=255),
        ),
    ]
