# Generated by Django 5.2 on 2025-07-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_engagement', '0004_alter_item_state_location_community_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('UNMODERATED', 'UNMODERATED'), ('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED'), ('ASSIGNED', 'ASSIGNED'), ('INPROGRESS', 'INPROGRESS'), ('RESOLVED', 'RESOLVED'), ('ACCEPTED_STAGE_1', 'ACCEPTED_STAGE_1'), ('ACCEPTED_STAGE_2', 'ACCEPTED_STAGE_2'), ('REJECTED_STAGE_1', 'REJECTED_STAGE_1'), ('REJECTED_STAGE_2', 'REJECTED_STAGE_2')], max_length=255),
        ),
    ]
