# configuration values for the project

GEE_PROJECT_NAME = 'raman-461708'	# Google Earth Engine project name

GEE_SCALE = 30 # in meters

# Path to the GeoJSON file defining the region of interest
# Currently, this can be provided with command line arguments.
BOUNDARY_GEOJSON_PATH = './tifs/delhi.geojson'

# The following tifs will be downloaded by scripts.
DEMFILE_PATH = './tifs/dem.tif'
SOIL_PATH = './data/base_layers/soil/hysogs_india_250m_4326.tif'
LULC_PATH = './data/base_layers/lulc/lulc_v3_2024_2025.tif'
LULC_SOURCE = 'indiasatv3'
INDIASATV3_LULC_PATH = './data/base_layers/lulc/lulc_v3_2024_2025.tif'

# Folder where rainfall data from GEE is downloaded to
RAINFALL_FOLDER = './tifs/rainfall3/'
RUNOFFS_FOLDER = './tifs/runoffs3/'

# The output file.
TIMESERIES_VECTOR = './tifs/timeseries.geojson'

ARG_START_DATE = '2017-07-01'
ARG_END_DATE = '2025-06-18'
