workspace_config = {
    "Admin Boundaries": {"name": "panchayat_boundaries", "type": "vector"},
    "NREGA Assets": {"name": "nrega_assets", "type": "vector"},
    "Drought Frequency": {
        "name": "drought",
        "suffix": "drought",
        "type": "vector",
    },
    "Drainage Lines": {"name": "drainage", "type": "vector"},
    "drought_causality": {
        "name": "drought_causality",
        "suffix": "drought_causality",
        "type": "vector",
    },
    "Surface Water Bodies": {
        "name": "swb",
        "prefix": "surface_waterbodies",
        "type": "vector",
    },
    "clart": {"name": "clart", "suffix": "clart", "type": "raster"},
    "MWS fortnightly ": {
        "name": "mws_layers",
        "prefix": "deltaG_fortnight",
        "type": "vector",
    },
    "MWS well depth yearly": {
        "name": "mws_layers",
        "prefix": "deltaG_well_depth",
        "type": "vector",
    },
    "Cropping Intensity": {
        "name": "crop_intensity",
        "suffix": "intensity",
        "type": "vector",
    },
    "Crop Grids": {"name": "crop_grid_layers", "suffix": "grid", "type": "vector"},
    "restoration_raster": {
        "name": "restoration",
        "prefix": "restoration",
        "suffix": "raster",
        "type": "raster",
    },
    "restoration": {
        "name": "restoration",
        "prefix": "restoration",
        "suffix": "vector",
        "type": "vector",
    },
    "stream_order_raster": {
        "name": "stream_order",
        "prefix": "stream_order",
        "suffix": "raster",
        "type": "raster",
    },
    "stream_order_vector": {
        "name": "stream_order",
        "prefix": "stream_order",
        "suffix": "vector",
        "type": "vector",
    },
    "change_detection_Afforestation_raster": {
        "name": "change_detection",
        "prefix": "change",
        "suffix": "Afforestation",
        "type": "raster",
    },
    "change_detection_CropIntensity_raster": {
        "name": "change_detection",
        "prefix": "change",
        "suffix": "CropIntensity",
        "type": "raster",
    },
    "change_detection_Deforestation_raster": {
        "name": "change_detection",
        "prefix": "change",
        "suffix": "Deforestation",
        "type": "raster",
    },
    "change_detection_Degradation_raster": {
        "name": "change_detection",
        "prefix": "change",
        "suffix": "Degradation",
        "type": "raster",
    },
    "change_detection_Urbanization_raster": {
        "name": "change_detection",
        "prefix": "change",
        "suffix": "Urbanization",
        "type": "raster",
    },
    "change_detection_Afforestation_vector": {
        "name": "change_detection",
        "prefix": "change_vector",
        "suffix": "Afforestation",
        "type": "vector",
    },
    "change_detection_CropIntensity_vector": {
        "name": "change_detection",
        "prefix": "change_vector",
        "suffix": "CropIntensity",
        "type": "vector",
    },
    "change_detection_Deforestation_vector": {
        "name": "change_detection",
        "prefix": "change_vector",
        "suffix": "Deforestation",
        "type": "vector",
    },
    "change_detection_Degradation_vector": {
        "name": "change_detection",
        "prefix": "change_vector",
        "suffix": "Degradation",
        "type": "vector",
    },
    "change_detection_Urbanization_vector": {
        "name": "change_detection",
        "prefix": "change_vector",
        "suffix": "Urbanization",
        "type": "vector",
    },
    "Terrain Cluster": {"name": "terrain", "suffix": "cluster", "type": "vector"},
    "Terrain Raster": {"name": "terrain", "suffix": "terrain_raster", "type": "raster"},
    "terrain_lulc_plain": {
        "name": "terrain_lulc",
        "suffix": "lulc_plain",
        "type": "vector",
    },
    "terrain_lulc_slope": {
        "name": "terrain_lulc",
        "suffix": "lulc_slope",
        "type": "vector",
    },
    "aquifer": {"name": "aquifer", "prefix": "aquifer_vector", "type": "vector"},
    "soge": {"name": "soge", "prefix": "soge_vector", "type": "vector"},
    "tree_overall_ch_raster": {
        "name": "tree_overall_ch",
        "prefix": "overall_change_raster",
        "type": "raster",
    },
    "tree_overall_ch_vector": {
        "name": "tree_overall_ch",
        "prefix": "overall_change_vector",
        "type": "vector",
    },
    "Canopy height raster 2017": {
        "name": "canopy_height",
        "prefix": "ch_raster",
        "suffix": "2017",
        "type": "raster",
    },
    "Canopy height raster 2018": {
        "name": "canopy_height",
        "prefix": "ch_raster",
        "suffix": "2018",
        "type": "raster",
    },
    "Canopy height raster 2019": {
        "name": "canopy_height",
        "prefix": "ch_raster",
        "suffix": "2019",
        "type": "raster",
    },
    "Canopy height raster 2020": {
        "name": "canopy_height",
        "prefix": "ch_raster",
        "suffix": "2020",
        "type": "raster",
    },
    "Canopy height raster 2021": {
        "name": "canopy_height",
        "prefix": "ch_raster",
        "suffix": "2021",
        "type": "raster",
    },
    "Canopy height raster 2022": {
        "name": "canopy_height",
        "prefix": "ch_raster",
        "suffix": "2022",
        "type": "raster",
    },
    "Canopy height raster 2023": {
        "name": "canopy_height",
        "prefix": "ch_raster",
        "suffix": "2023",
        "type": "raster",
    },
    "Canopy height vector": {
        "name": "canopy_height",
        "prefix": "ch_vector",
        "suffix": "2017_2023",
        "type": "vector",
    },
    "Ccd raster 2017": {
        "name": "ccd",
        "prefix": "ccd_raster",
        "suffix": "2017",
        "type": "raster",
    },
    "Ccd raster 2018": {
        "name": "ccd",
        "prefix": "ccd_raster",
        "suffix": "2018",
        "type": "raster",
    },
    "Ccd raster 2019": {
        "name": "ccd",
        "prefix": "ccd_raster",
        "suffix": "2019",
        "type": "raster",
    },
    "Ccd raster 2020": {
        "name": "ccd",
        "prefix": "ccd_raster",
        "suffix": "2020",
        "type": "raster",
    },
    "Ccd raster 2021": {
        "name": "ccd",
        "prefix": "ccd_raster",
        "suffix": "2021",
        "type": "raster",
    },
    "Ccd raster 2022": {
        "name": "ccd",
        "prefix": "ccd_raster",
        "suffix": "2022",
        "type": "raster",
    },
    "Ccd raster 2023": {
        "name": "ccd",
        "prefix": "ccd_raster",
        "suffix": "2023",
        "type": "raster",
    },
    "Ccd vector": {
        "name": "ccd",
        "prefix": "ccd_vector",
        "suffix": "2017_2023",
        "type": "vector",
    },
    "LULC_level_1 LULC_17_18": {
        "name": "LULC_level_1",
        "prefix": "LULC_17_18",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_1 LULC_18_19": {
        "name": "LULC_level_1",
        "prefix": "LULC_18_19",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_1 LULC_19_20": {
        "name": "LULC_level_1",
        "prefix": "LULC_19_20",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_1 LULC_20_21": {
        "name": "LULC_level_1",
        "prefix": "LULC_20_21",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_1 LULC_21_22": {
        "name": "LULC_level_1",
        "prefix": "LULC_21_22",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_1 LULC_22_23": {
        "name": "LULC_level_1",
        "prefix": "LULC_22_23",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_1 LULC_23_24": {
        "name": "LULC_level_1",
        "prefix": "LULC_23_24",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_1 LULC_24_25": {
        "name": "LULC_level_1",
        "prefix": "LULC_24_25",
        "suffix": "level_1",
        "type": "raster",
    },
    "LULC_level_2 LULC_17_18": {
        "name": "LULC_level_2",
        "prefix": "LULC_17_18",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_2 LULC_18_19": {
        "name": "LULC_level_2",
        "prefix": "LULC_18_19",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_2 LULC_19_20": {
        "name": "LULC_level_2",
        "prefix": "LULC_19_20",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_2 LULC_20_21": {
        "name": "LULC_level_2",
        "prefix": "LULC_20_21",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_2 LULC_21_22": {
        "name": "LULC_level_2",
        "prefix": "LULC_21_22",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_2 LULC_22_23": {
        "name": "LULC_level_2",
        "prefix": "LULC_22_23",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_2 LULC_23_24": {
        "name": "LULC_level_2",
        "prefix": "LULC_23_24",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_2 LULC_24_25": {
        "name": "LULC_level_2",
        "prefix": "LULC_24_25",
        "suffix": "level_2",
        "type": "raster",
    },
    "LULC_level_3 LULC_17_18": {
        "name": "LULC_level_3",
        "prefix": "LULC_17_18",
        "suffix": "level_3",
        "type": "raster",
    },
    "LULC_level_3 LULC_18_19": {
        "name": "LULC_level_3",
        "prefix": "LULC_18_19",
        "suffix": "level_3",
        "type": "raster",
    },
    "LULC_level_3 LULC_19_20": {
        "name": "LULC_level_3",
        "prefix": "LULC_19_20",
        "suffix": "level_3",
        "type": "raster",
    },
    "LULC_level_3 LULC_20_21": {
        "name": "LULC_level_3",
        "prefix": "LULC_20_21",
        "suffix": "level_3",
        "type": "raster",
    },
    "LULC_level_3 LULC_21_22": {
        "name": "LULC_level_3",
        "prefix": "LULC_21_22",
        "suffix": "level_3",
        "type": "raster",
    },
    "LULC_level_3 LULC_22_23": {
        "name": "LULC_level_3",
        "prefix": "LULC_22_23",
        "suffix": "level_3",
        "type": "raster",
    },
    "LULC_level_3 LULC_23_24": {
        "name": "LULC_level_3",
        "prefix": "LULC_23_24",
        "suffix": "level_3",
        "type": "raster",
    },
    "LULC_level_3 LULC_24_25": {
        "name": "LULC_level_3",
        "prefix": "LULC_24_25",
        "suffix": "level_3",
        "type": "raster",
    },
    "lulc_vector": {"name": "lulc_vector", "prefix": "lulc_vector", "type": "vector"},
    "natural_depression": {
        "name": "natural_depression",
        "prefix": "natural_depression",
        "suffix": "raster",
        "type": "raster",
    },
    "Distance to Drainage Line": {
        "name": "distance_nearest_upstream_DL",
        "prefix": "distance_to_drainage_line",
        "suffix": "raster",
        "type": "raster",
    },
    "generate_catchment_area_singleflow": {
        "name": "catchment_area_singleflow",
        "prefix": "catchment_area",
        "suffix": "raster",
        "type": "raster",
    },
    "generate_slope_percentage": {
        "name": "catchment_area_singleflow",
        "suffix": "slope_percentage_raster",
        "type": "raster",
    },
    "generate_lcw": {
        "name": "lcw",
        "suffix": "lcw_conflict",
        "type": "vector",
    },
    "agroecological": {
        "name": "agroecological",
        "suffix": "agroecological",
        "type": "vector",
    },
    "generate_factory_csr": {
        "name": "factory_csr",
        "suffix": "factory_csr",
        "type": "vector",
    },
    "generate_green_credit": {
        "name": "green_credit",
        "suffix": "green_credit",
        "type": "vector",
    },
    "generate_mining": {
        "name": "green_credit",
        "suffix": "green_credit",
        "type": "vector",
    },
}
