<<<<<<< HEAD
# Generated by Django 5.2 on 2025-06-24 09:03
=======
# Generated by Django 5.2 on 2025-06-24 15:19
>>>>>>> layer/save_db

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('layer_type', models.CharField(blank=True, choices=[('vector', 'Vector'), ('raster', 'Raster'), ('point', 'Point'), ('custom', 'Custom')], max_length=50, null=True)),
                ('misc', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(blank=True, max_length=511, null=True)),
                ('layer_version', models.CharField(blank=True, max_length=255, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=511, null=True)),
                ('algorithm_version', models.CharField(blank=True, max_length=255, null=True)),
                ('style_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_excel_generated', models.BooleanField(blank=True, default=False, null=True)),
                ('gee_asset_path', models.CharField(blank=True, max_length=511, null=True)),
                ('is_public_gee_asset', models.BooleanField(default=False)),
                ('workspace', models.CharField(blank=True, max_length=255, null=True)),
                ('misc', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computing.dataset')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
            },
        ),
    ]
