# Generated by Django 5.2 on 2025-05-14 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_type', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster'), ('point', 'Point'), ('custom', 'Custom')], max_length=50)),
                ('gee_asset_path', models.CharField(blank=True, max_length=511, null=True)),
                ('is_public_gee_asset', models.BooleanField(default=False)),
                ('algorithm', models.CharField(blank=True, max_length=511, null=True)),
                ('algorithm_version', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace', models.CharField(blank=True, max_length=255, null=True)),
                ('layer_name', models.CharField(blank=True, max_length=511, null=True)),
                ('layer_version', models.CharField(blank=True, max_length=255, null=True)),
                ('style_name', models.CharField(blank=True, max_length=255, null=True)),
                ('misc', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
            ],
        ),
    ]
