# Generated by Django 5.0.7 on 2025-04-08 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing', '0001_initial'),
        ('geoadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLayerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('raster', 'Raster'), ('vector', 'Vector')], max_length=255)),
                ('gee_path', models.JSONField(blank=True, null=True)),
                ('workspace', models.CharField(max_length=512)),
                ('algorithm', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('style_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('misc', models.JSONField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.block')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_layer', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoadmin.state')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_layer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='LayerInfo',
        ),
    ]
