# Generated by Django 5.0.7 on 2025-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedlayerinfo',
            name='layer_type',
            field=models.CharField(choices=[('raster', 'Raster'), ('vector', 'Vector')], max_length=255),
        ),
    ]
