# Generated by Django 5.2 on 2025-07-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='algorithm_version',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='layer_version',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='style_name',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='workspace',
        ),
        migrations.AddField(
            model_name='dataset',
            name='algorithm',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='algorithm_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='layer_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='style_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='workspace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='gee_asset_path',
            field=models.CharField(blank=True, default='not available', max_length=511, null=True),
        ),
    ]
