# Generated by Django 5.0.7 on 2025-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing', '0002_generatedlayerinfo_delete_layerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedlayerinfo',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generatedlayerinfo',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
