# Generated by Django 5.0.7 on 2025-03-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computing', '0003_layerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerinfo',
            name='version',
        ),
        migrations.AlterField(
            model_name='layerinfo',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layerinfo',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layerinfo',
            name='style_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
