# Generated by Django 5.2 on 2025-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computing", "0004_dataset_created_by_dataset_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="created_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="layer",
            name="is_sync_to_geoserver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="layer",
            name="updated_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
