# Generated by Django 5.2 on 2025-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computing", "0005_layer_created_by_layer_is_sync_to_geoserver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="is_override",
            field=models.BooleanField(default=False),
        ),
    ]
